// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SlctdChecklist.Models;

#nullable disable

namespace SlctdChecklist.Migrations
{
    [DbContext(typeof(ChecklistDbContext))]
    [Migration("20260415194040_Restructure1")]
    partial class Restructure1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("SegmentShiftTask", b =>
                {
                    b.Property<int>("ParentSegmentsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TasksToDoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ParentSegmentsId", "TasksToDoId");

                    b.HasIndex("TasksToDoId");

                    b.ToTable("SegmentShiftTask");
                });

            modelBuilder.Entity("SlctdChecklist.Models.Checklist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Shift")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Checklist", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("SlctdChecklist.Models.Segment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChecklistId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("DueBy")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("StartBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistId");

                    b.ToTable("Segments");
                });

            modelBuilder.Entity("SlctdChecklist.Models.ShiftTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ShiftTask", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("SlctdChecklist.Models.ChecklistSubmission", b =>
                {
                    b.HasBaseType("SlctdChecklist.Models.Checklist");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Employee")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("ChecklistSubmissions", (string)null);
                });

            modelBuilder.Entity("SlctdChecklist.Models.CompletionRecord", b =>
                {
                    b.HasBaseType("SlctdChecklist.Models.ShiftTask");

                    b.Property<bool>("Done")
                        .HasColumnType("INTEGER");

                    b.ToTable("CompletionRecords", (string)null);
                });

            modelBuilder.Entity("SegmentShiftTask", b =>
                {
                    b.HasOne("SlctdChecklist.Models.Segment", null)
                        .WithMany()
                        .HasForeignKey("ParentSegmentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SlctdChecklist.Models.ShiftTask", null)
                        .WithMany()
                        .HasForeignKey("TasksToDoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SlctdChecklist.Models.Segment", b =>
                {
                    b.HasOne("SlctdChecklist.Models.Checklist", "ParentChecklist")
                        .WithMany("Segments")
                        .HasForeignKey("ChecklistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentChecklist");
                });

            modelBuilder.Entity("SlctdChecklist.Models.ChecklistSubmission", b =>
                {
                    b.HasOne("SlctdChecklist.Models.Checklist", null)
                        .WithOne()
                        .HasForeignKey("SlctdChecklist.Models.ChecklistSubmission", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SlctdChecklist.Models.CompletionRecord", b =>
                {
                    b.HasOne("SlctdChecklist.Models.ShiftTask", null)
                        .WithOne()
                        .HasForeignKey("SlctdChecklist.Models.CompletionRecord", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SlctdChecklist.Models.Checklist", b =>
                {
                    b.Navigation("Segments");
                });
#pragma warning restore 612, 618
        }
    }
}
